### PR TITLE
index.html, corrected a spelling mistake : usually

### PR DESCRIPTION
**Pull request by Quantum-Codes**
### What i changed:
Usually was of wrong spelling...
Anyway---> anyways 
Etheir  ----> either
Parces ----> parses 
Yay, my first commit on someone else's project
### Suggestions?
I think scratch addons makes scratch 1000x better
A `<hr>` tag below blog title could be good? (Idk... I know basic only)

### CODE REVIEW

**Comment by Quantum-Codes** [comment]
@TheColaber  hi?

**Comment by TheColaber** [comment]
oh uh

**Comment by Quantum-Codes** [comment]
I saw another of a pull request on your repo... that said simply commiting spellings isn't good and we will be banned from the repo... can u say about it?

**Comment by TheColaber** [comment]
That's not what I said. What I said was spamming useless PRs such as changing a couple of words in a readme can get you banned from major repositories such as github/docs. Usually, it's not proper to join github just to change other people's readmes and websites. It is for creating your own things.

**Comment by Quantum-Codes** [comment]
Oh. So this is ok right? The commit I did?

**Comment by TheColaber** [comment]
Probably

**Pull request merged**
